import Head from "next/head";
import { Row, Typography, Col, Statistic } from "antd";
import Link from "next/link";
import { useGetCryptosQuery } from "../services/cryptoapi";
import millify from "millify";
import {Cryptocurrencies, News, Loader} from "../components";

export default function Home() {
  const { data, isFetching } = useGetCryptosQuery(10);
  const globalStats = data?.data?.stats;
  if (isFetching) return <Loader />;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography.Title level={2} className="heading">
        Globel Crypto State
      </Typography.Title>
      <Row>
        <Col span={12}>
          <Statistic title="Total Crypotcurrencies" value={globalStats?.total} />
        </Col>
        <Col span={12}>
          <Statistic
            title="Total Exchanges"
            value={millify(globalStats?.totalExchanges)}
          />
        </Col>
        <Col span={12}>
          <Statistic
            title="Total Market Cap"
            value={millify(globalStats?.totalMarketCap)}
          />
        </Col>
        <Col span={12}>
          <Statistic
            title="Total 24h Volume"
            value={millify(globalStats?.total24hVolume)}
          />
        </Col>
        <Col span={12}>
          <Statistic
            title="Total Markets"
            value={millify(globalStats?.totalMarkets)}
          />
        </Col>
      </Row>

      <div className="home-heading-container">
        <Typography.Title level={2} className="home-title">
          Top 10 Cryptocurrencies in the world
        </Typography.Title>
        <Typography.Title level={3} className="show-more">
          <Link href="/crypocurrencies">
            <a>Show More</a>
          </Link>
        </Typography.Title>
      </div>
      <Cryptocurrencies simplified />
      <div className="home-heading-container">
        <Typography.Title level={2} className="home-title">
          Latest Crypto News
        </Typography.Title>
        <Typography.Title level={3} className="show-more">
          <Link href="/news">
            <a>Show More</a>
          </Link>
        </Typography.Title>
      </div>
      <News simplified />
    </>
  );
}
